eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8282/eureka

server:
  port: 8090
spring:
  application:
    name: product
  config:
    import: optional:configserver:http://localhost:8888
